version: 1.2.2.{build}-beta
os: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: >-
    nuget restore .\MvvmHelpers.sln


    powershell .\bootstrapper.ps1 -Target Default -Verbosity diagnostic

    powershell .\bootstrapper.ps1 -Target NuGetPack -Verbosity diagnostic
artifacts:
- path: '*.nupkg'
  name: NuGet
